import  Mycontext  from '@/helper/Context'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
Mycontext
  return (
    <html lang="en">
      <body suppressContentEditableWarning>
        <Mycontext>
        {children}
        </Mycontext>
      </body>
    </html>
  )
}
